#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_NAME="kgb_info_top_hud.amxx"
PLUGIN_SOURCE="$ROOT_DIR/compiled/$PLUGIN_NAME"

usage() {
	printf 'Usage: %s <server-root>\n' "${0##*/}" >&2
	printf 'Installs the plugin and adds %s to addons/amxmodx/configs/plugins.ini if missing.\n' "$PLUGIN_NAME" >&2
}

if test "$#" -ne 1; then
	usage
	exit 2
fi

SERVER_ROOT="$1"
PLUGIN_DIR="$SERVER_ROOT/addons/amxmodx/plugins"
CONFIG_DIR="$SERVER_ROOT/addons/amxmodx/configs"
PLUGINS_INI="$CONFIG_DIR/plugins.ini"

if ! test -f "$PLUGIN_SOURCE"; then
	"$ROOT_DIR/scripts/build.sh"
fi

mkdir -p "$PLUGIN_DIR" "$CONFIG_DIR"
cp "$PLUGIN_SOURCE" "$PLUGIN_DIR/$PLUGIN_NAME"

if ! test -f "$PLUGINS_INI"; then
	{
		printf '; AMX Mod X plugins\n'
		printf '; Generated by kgb-info-top-hud install script.\n'
		printf '%s\n' "$PLUGIN_NAME"
	} > "$PLUGINS_INI"
	printf 'Created %s\n' "$PLUGINS_INI"
	exit 0
fi

if awk -v plugin="$PLUGIN_NAME" '
	{
		line = $0
		sub(/^[[:space:]]+/, "", line)
		sub(/[[:space:]]+$/, "", line)
		if (line == plugin || line ~ "^" plugin "[[:space:]]") {
			found = 1
		}
	}
	END { exit found ? 0 : 1 }
' "$PLUGINS_INI"; then
	printf 'Plugin entry already present in %s\n' "$PLUGINS_INI"
	exit 0
fi

if awk -v plugin="$PLUGIN_NAME" '
	{
		line = $0
		sub(/^[[:space:]]+/, "", line)
		if (line ~ "^;" "[[:space:]]*" plugin "([[:space:]]|$)") {
			found = 1
		}
	}
	END { exit found ? 0 : 1 }
' "$PLUGINS_INI"; then
	printf 'Plugin entry is present but disabled in %s; leaving it unchanged.\n' "$PLUGINS_INI"
	exit 0
fi

{
	printf '\n'
	printf '%s\n' "$PLUGIN_NAME"
} >> "$PLUGINS_INI"

printf 'Added plugin entry to %s\n' "$PLUGINS_INI"
